#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# Route for displaying all active articles
#article_list:
#path: /articles
#controller: App\Controller\ArticleController::index
#methods: GET

# Route for creating a new article
#article_create:
#path: /articles
#controller: App\Controller\ArticleController::create
#methods: POST
